server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    account-by-address:
      path: /account-by-address/**
      url: http://localhost:9092
    account-by-service:
      path: /account-by-service/**
      serviceId: ACCOUNT-SERVICE
    node-by-address:
      path: /node-by-address/**
      url: http://localhost:9091
    node-by-service:
      path: /node-by-service/**
      serviceId: NODE-SERVICE
    static:
      path: /static/**

spring:
  application:
    name: zuul-api-gateway-server